spring.application.name=CategoriasAPI

# MYSQL
spring.datasource.url=${MYSQL_URL:jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:categoriasdb}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update

# MOSTRAR SQL
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

# Railway asigna PORT en producción.
server.port=${PORT:8080}
